---
- hosts: all
  become: yes
  become_user: root
  vars:
    password : psw
    userid: userid
    username : usrname
    tasks :
    - name : User Exist
      shell: id{{ username }}
      register: user_exist
      ignore_errors: yes
    - debug: msg="User Name {{ username }} is not exist in {{ ansible_hostsname }}"
      when : user_exist.rc !=0
    - name : Password reset
      user : name={{ username }} password_update=always password={{ password }}
      when : user_exist.rc ==0
      register: passwd_reset
    - debug: msg="Password Has been reset for the user {{ username }} om {{ ansible_hostsname }} "
      when : passwd_reset.changed