---
- hosts : localhost
  pre_tasks:
  #Here will define the task one by one
  #define the installation of remi repo node js
     - name : Install Remi Repo
       yum :
         name : "https://rpms.remirepo.net/enterprise/remi-release-7.rpm"
          state : present

     - name : Import Remi GPG key .
       rpm_key :
          key : "https://rpms.remirepo.net/RPM-GPG-KEY-remi"
          state: present

     - name: Install EPEL repo
       yum: name=epel-release state=present

     - name: Ensure failwall is stopped (since this is for testing)
       service: name=firewalld state=stopped
 roles :
   - nodejs

tasks :
  #copy the app in terget location to npm to download the dependencies
  - name:   Ensure node.js app folde exist
    file: "path={{ node_apps_location }} state=directory"
  - name: copy the example Node.js app to server .
    #      copy : "src=../configs/node_application/* dest={{ node_apps_location }}/app"
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: 0644
    with_items:
      - src: "../configs/node_application/app.js"
        dest: "{{ node_apps_location }}/app/"
      - src: "../configs/node_application/package.json"
        dest: "{{ node_apps_location }}/app/"
  - name: Install app dependencies define in package.json
    npm: path={{ node_apps_location }}/app

  #Use forever to start the application
  - name: Check list of running Node.js apps .
    command: forever list
    register: forever_list
    changed_when: false
  - name: Start Example Node.js app.
    command: "forever start {{ node_apps_location }}/app/app.js"
    when: "forever_list.stdout.find(node_apps_location + \
        '/app/app.js')== -1"
