---
- hosts : localhost
  vars_files:
    - var.yaml
  pre_tasks :
    - name : update apt cache if needded
      apt : update_cache=yes cache_valid_time=3600
  handlers :
    - name: Restart solr
      service : name=solr state=restarted
# install jdk8
  tasks :
    - name : Install java
      apt: name=open jdk-8-jdk state=present
# Download and Install apache solr
    - name : Download Apache solr
      get_url:
        url : "https://archive.apache.org/dist/lucene/solr/\
        {{ solr_version }}/solr-{{ solr_version }}.tgz"
        dest: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        checksum: "{{ solr_checksum }}"
    - name : Expand Solr
      unarchive:
        src : "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        dest : "{{ download_dir }}"
        copy : no
        creates: "{{ download_dir }}/solr-{{ solr_version }}/\
          README.txt"
    - name : Run solr Install script
      shell : >
        {{ download_dir }}/solr-{{ solr_version }}/bin/install_solr_ser\
        vice.sh
        {{ download_dir }}/solr-{{ solr_version }}.tgz
        -i /opt
        -d /var/solr
        -u solr
        -s solr
        -p 8983
        creates={{ solr_dir }}/bin/solr
#start solr server
    - name : Ensure solr is started and enabled on boot
      service : name=solr state=started enabled=yes


